name: Build-Ubuntu-22.04

on:
  push:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install prerequisites
        run: >-
          sudo apt-get update

          sudo apt-get install -y
          build-essential
          g++
          qt6-base-dev
          qt6-l10n-tools
          qt6-multimedia-dev
          qt6-tools-dev-tools
          qt6-tools-dev
          qmake6
          libqt6multimedia6
          libqt6serialport6-dev
          linguist-qt6
          libhamlib-dev
          libv4l-dev
          libfftw3-dev
          libasound2-dev
          libopenjp2-7-dev
          libpulse-dev

          # see https://askubuntu.com/questions/1460242/ubuntu-22-04-with-qt6-qmake-could-not-find-a-qt-installation-of

          qtchooser -install qt6 $(which qmake6)
      - name: Run Qmake
        run: >-
          mkdir src/build;
          cd src/build;
          qmake --qt=qt6 ../qsstv.pro
      - name: Build
        run: >-
          cd src/build;
          make
